### PR TITLE
Update settings on main and edit pages

### PR DESCRIPTION
**Pull request by davidpbauer**
Settings form post on main wasn't handled
Missing settings form on the edit page

### CODE REVIEW

**Comment by csev** [comment]
Thanks for cleaning up my little mistakes.

**Comment by davidpbauer** [comment]
Happy to help! Thanks for making this tool, it's very cool.

**Comment by csev** [comment]
And I used / improved your new menu approach and made it work for settings.  I like it.

**Comment by davidpbauer** [comment]
I like the way you did settings and help. Previously, I've always added them as links on the page instead of in the menu, but having the option to just add them to the menu like you did is great.

**Pull request merged**
